# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 14:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(max_length=20)),
                ('activation_deadline', models.DateField()),
                ('activated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('type', models.CharField(default='tag', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField()),
                ('problem_description_html', models.TextField()),
                ('example_input', models.TextField(default='No example input provided.')),
                ('example_input_html', models.TextField()),
                ('example_output', models.TextField(default='No example output provided.')),
                ('example_output_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField(choices=[(0, 'Very Easy'), (1, 'Easy'), (2, 'Average'), (3, 'Difficult'), (4, 'Very Difficult')], default=0)),
                ('private', models.BooleanField(default=True)),
                ('forked_from', models.CharField(default='Original', max_length=200)),
                ('categories', models.ManyToManyField(to='problems.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_description', models.TextField(default='No solution description has been provided.')),
                ('solution_description_html', models.TextField()),
                ('time_limit', models.FloatField(default=0)),
                ('links', models.TextField(default='No links.')),
                ('links_html', models.TextField()),
                ('example_code', models.TextField(default='No example solution code.')),
                ('example_code_html', models.TextField()),
                ('language', models.CharField(default='No example solution code.', max_length=200)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='problems',
            field=models.ManyToManyField(to='problems.Problem'),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set([('title',)]),
        ),
    ]
